<?php

namespace SOCIALFORUM;

use SilverStripe\Control\HTTPRequest;
use SilverStripe\Dev\Debug;
use SilverStripe\View\Requirements;

/**
 * Description
 *
 * @package silverstripe
 * @subpackage mysite
 */
class ForumPageController extends \PageController
{

    private static $allowed_actions = [
        'SaveSubmission'
    ];

    private static $url_handlers = [
        'save/$forumID' => 'SaveSubmission'
    ];

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Requirements::themedJavascript('assets/javascript/index/index.js');
    }

    /**
     * Gets the the approved submissions
     */
    public function getSubmissions() {
        $submissions = ForumSubmission::get()
            ->filter(['ForumPageID' => $this->ID, 'Approved' => 1])
            ->sort('Created', 'ASC');
        return $submissions;
    }

    public function SaveSubmission(HTTPRequest $request){
        $response = (object)['success' => false, 'message' => null, 'data' => null];
        $forumPage = $request->param('forumID');
        if($forumPage){
            Debug::dump("submission is being executed");
        }else{
            $response->message = "Forum page with id: " . $forumPage . ' does not exist';
        }
        return $this->getResponse()
            ->addHeader('Content-Type', 'application/json')
            ->setBody(json_encode($response));
    }
}
