<?php

namespace SOCIALFORUM;

use SilverStripe\View\Requirements;

/**
 * Description
 *
 * @package silverstripe
 * @subpackage mysite
 */
class ForumPageController extends \PageController
{

  /**
  * Gets the the approved submissions
  */
  public function getSubmissions() {
    $submissions = ForumSubmission::get()
    ->filter(['ForumPageID' => $this->ID, 'Approved' => 1])
    ->sort('Created', 'ASC');
    return $submissions;
  }

  protected function init()
  {
      parent::init(); // TODO: Change the autogenerated stub
      Requirements::themedJavascript('assets/javascript/index/index.js');
  }
}
